spring.application.name=gateway
server.port=8081
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=medilabo_gateway
spring.config.import=optional:configserver:

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false




internal.secret=password_has_to_be_changed